// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using challengeFiap.src.Data;

#nullable disable

namespace challengeFiap.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523135955_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("challengeFiap.src.Models.Animal", b =>
                {
                    b.Property<int>("Id_animal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_animal");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_animal"));

                    b.Property<DateTime>("Dt_nascimento_animal")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_nascimento_animal");

                    b.Property<string>("Especie_animal")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("especie_animal");

                    b.Property<int>("Id_responsavel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_responsavel");

                    b.Property<string>("Nm_animal")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_animal");

                    b.Property<string>("Nr_microchip_animal")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nr_microchip_animal");

                    b.Property<decimal>("Peso_animal")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("peso_animal");

                    b.Property<string>("Raca_animal")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("raca_animal");

                    b.Property<string>("Rg_animal")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("rg_animal");

                    b.HasKey("Id_animal");

                    b.HasIndex("Id_responsavel");

                    b.ToTable("T_CLYVO_ANIMAL", (string)null);
                });

            modelBuilder.Entity("challengeFiap.src.Models.CarteiraVacinal", b =>
                {
                    b.Property<int>("Id_carteiraVacinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_carteiravacinal");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_carteiraVacinal"));

                    b.Property<DateTime>("Dt_vacina_efetuada")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_vacinacao_efetuada");

                    b.Property<DateTime>("Dt_vacina_prevista")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_vacinacao_prevista");

                    b.Property<int>("Id_animal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_animal");

                    b.Property<string>("Nm_vacina")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_vacina");

                    b.Property<string>("St_vacina")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("st_vacinacao");

                    b.HasKey("Id_carteiraVacinal");

                    b.HasIndex("Id_animal");

                    b.ToTable("T_CLYVO_CARTEIRAVACINAL", (string)null);
                });

            modelBuilder.Entity("challengeFiap.src.Models.Clinica", b =>
                {
                    b.Property<int>("Id_clinica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_clinica");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_clinica"));

                    b.Property<string>("Cnpj_clinica")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cnpj_clinica");

                    b.Property<string>("Nm_clinica")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_clinica");

                    b.HasKey("Id_clinica");

                    b.ToTable("T_CLYVO_CLINICA", (string)null);
                });

            modelBuilder.Entity("challengeFiap.src.Models.Consulta", b =>
                {
                    b.Property<int>("Id_consulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_consulta");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_consulta"));

                    b.Property<DateTime>("Dt_consulta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_consulta");

                    b.Property<string>("Historico_consulta")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("historico_consulta");

                    b.Property<int>("Id_animal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_animal");

                    b.Property<int>("Id_vet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_vet");

                    b.Property<string>("St_consulta")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("st_consulta");

                    b.HasKey("Id_consulta");

                    b.HasIndex("Id_animal");

                    b.HasIndex("Id_vet");

                    b.ToTable("T_CLYVO_CONSULTA", (string)null);
                });

            modelBuilder.Entity("challengeFiap.src.Models.EnderecoAnimal", b =>
                {
                    b.Property<int>("Id_endereco_animal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_endereco_animal");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_endereco_animal"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("complemento");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("estado");

                    b.Property<int>("Id_animal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_animal");

                    b.Property<string>("Logradouro_rua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("logradouro_rua");

                    b.Property<string>("Nr_rua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nr_rua");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("pais");

                    b.HasKey("Id_endereco_animal");

                    b.HasIndex("Id_animal");

                    b.ToTable("T_CLYVO_ENDERECO_ANIMAL", (string)null);
                });

            modelBuilder.Entity("challengeFiap.src.Models.EnderecoClinica", b =>
                {
                    b.Property<int>("Id_endereco_clinica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_endereco_clinica");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_endereco_clinica"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("complemento");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("estado");

                    b.Property<int>("Id_clinica")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_clinica");

                    b.Property<string>("Logradouro_rua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("logradouro_rua");

                    b.Property<string>("Nr_rua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nr_rua");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("pais");

                    b.HasKey("Id_endereco_clinica");

                    b.HasIndex("Id_clinica");

                    b.ToTable("T_CLYVO_ENDERECO_CLINICA", (string)null);
                });

            modelBuilder.Entity("challengeFiap.src.Models.EnderecoResponsavel", b =>
                {
                    b.Property<int>("Id_endereco_responsavel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_endereco_responsavel");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_endereco_responsavel"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("complemento");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("estado");

                    b.Property<int>("Id_responsavel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_responsavel");

                    b.Property<string>("Logradouro_rua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("logradouro_rua");

                    b.Property<string>("Nr_rua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nr_rua");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("pais");

                    b.HasKey("Id_endereco_responsavel");

                    b.HasIndex("Id_responsavel");

                    b.ToTable("T_CLYVO_ENDERECO_RESPONSAVEL", (string)null);
                });

            modelBuilder.Entity("challengeFiap.src.Models.Medicamento", b =>
                {
                    b.Property<int>("Id_medicamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_medicamento");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_medicamento"));

                    b.Property<string>("Dosagem_medicamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("dosagem_medicamento");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("frequencia");

                    b.Property<int>("Id_prescricao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_prescricao");

                    b.Property<string>("Nm_medicamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_medicamento");

                    b.Property<int>("Qtd_dias")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("qtd_dias");

                    b.HasKey("Id_medicamento");

                    b.HasIndex("Id_prescricao");

                    b.ToTable("T_CLYVO_MEDICAMENTO", (string)null);
                });

            modelBuilder.Entity("challengeFiap.src.Models.Prescricao", b =>
                {
                    b.Property<int>("Id_prescricao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_prescricao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_prescricao"));

                    b.Property<DateTime>("Dt_emissao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_emissao");

                    b.Property<DateTime>("Dt_expiracao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_expiracao");

                    b.Property<int>("Id_consulta")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_consulta");

                    b.Property<string>("Observacoes_gerais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("observacoes_gerais");

                    b.HasKey("Id_prescricao");

                    b.HasIndex("Id_consulta")
                        .IsUnique();

                    b.ToTable("T_CLYVO_PRESCRICAO", (string)null);
                });

            modelBuilder.Entity("challengeFiap.src.Models.Responsavel", b =>
                {
                    b.Property<int>("Id_responsavel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_responsavel");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_responsavel"));

                    b.Property<string>("Cpf_responsavel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("cpf_responsavel");

                    b.Property<string>("Nm_responsavel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_responsavel");

                    b.Property<string>("Nr_telefone_responsavel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nr_telefone_responsavel");

                    b.HasKey("Id_responsavel");

                    b.HasIndex("Cpf_responsavel")
                        .IsUnique()
                        .HasDatabaseName("cpf_responsavel");

                    b.ToTable("T_CLYVO_RESPONSAVEL", (string)null);
                });

            modelBuilder.Entity("challengeFiap.src.Models.VetClinica", b =>
                {
                    b.Property<int>("Id_clinica_vet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_clinica_vet");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_clinica_vet"));

                    b.Property<int>("Id_clinica")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_clinica");

                    b.Property<int>("Id_vet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_vet");

                    b.HasKey("Id_clinica_vet");

                    b.HasIndex("Id_clinica");

                    b.HasIndex("Id_vet");

                    b.ToTable("T_CLYVO_VET_CLINICA", (string)null);
                });

            modelBuilder.Entity("challengeFiap.src.Models.Veterinario", b =>
                {
                    b.Property<int>("Id_vet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_vet");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_vet"));

                    b.Property<string>("Cpf_vet")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("cpf_vet");

                    b.Property<string>("Crmv_vet")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("crmv_vet");

                    b.Property<string>("Email_vet")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("email");

                    b.Property<string>("Nm_vet")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_vet");

                    b.Property<string>("Senha_vet")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("senha");

                    b.HasKey("Id_vet");

                    b.HasIndex("Cpf_vet")
                        .IsUnique()
                        .HasDatabaseName("cpf_vet");

                    b.HasIndex("Crmv_vet")
                        .IsUnique()
                        .HasDatabaseName("crmv_vet");

                    b.ToTable("T_CLYVO_VET", (string)null);
                });

            modelBuilder.Entity("challengeFiap.src.Models.Animal", b =>
                {
                    b.HasOne("challengeFiap.src.Models.Responsavel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("Id_responsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("challengeFiap.src.Models.CarteiraVacinal", b =>
                {
                    b.HasOne("challengeFiap.src.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("Id_animal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("challengeFiap.src.Models.Consulta", b =>
                {
                    b.HasOne("challengeFiap.src.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("Id_animal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("challengeFiap.src.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("Id_vet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("challengeFiap.src.Models.EnderecoAnimal", b =>
                {
                    b.HasOne("challengeFiap.src.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("Id_animal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("challengeFiap.src.Models.EnderecoClinica", b =>
                {
                    b.HasOne("challengeFiap.src.Models.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("Id_clinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("challengeFiap.src.Models.EnderecoResponsavel", b =>
                {
                    b.HasOne("challengeFiap.src.Models.Responsavel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("Id_responsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("challengeFiap.src.Models.Medicamento", b =>
                {
                    b.HasOne("challengeFiap.src.Models.Prescricao", "Prescricao")
                        .WithMany()
                        .HasForeignKey("Id_prescricao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescricao");
                });

            modelBuilder.Entity("challengeFiap.src.Models.Prescricao", b =>
                {
                    b.HasOne("challengeFiap.src.Models.Consulta", "Consulta")
                        .WithOne()
                        .HasForeignKey("challengeFiap.src.Models.Prescricao", "Id_consulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("challengeFiap.src.Models.VetClinica", b =>
                {
                    b.HasOne("challengeFiap.src.Models.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("Id_clinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("challengeFiap.src.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("Id_vet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Veterinario");
                });
#pragma warning restore 612, 618
        }
    }
}
